---
title: "data_exploration"
author: "Christian Stenbro"
date: "`r Sys.Date()`"
output: html_document
---

Data note: This script is using local paths, as we are not uploading the data to git...

This script: 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load("tidyverse",
               "rethinking")
```

# loading data

```{r}
data <- read_csv("/Users/christianstenbro/AU/MSc/ACM/data/assignment_3_data/Simonsen_clean.csv")
```
```{r}
summary(data)
```
Some basic questions:

What is the sample size? 

```{r}
n = length(unique(data$ID))
cat("n =", n)
```

How many trials pr. participant?

```{r}
data %>% group_by(ID) %>% count(.)
```

153 pr. participant.

```{r}
data %>% group_by(ID)
```


```{r}
#make plots
p1 <- ggplot(data, aes(x = GroupRating, y = SecondRating, color = FirstRating)) +
  
  #make jittered points
  geom_jitter(width = 0.5, height = 0.5, alpha = 0.3) +
  
  #make heat mapping of points based on feedback
  scale_color_continuous(high = "red", low = "blue") +
  
  #draw line of x=y
  geom_abline(linetype = "dashed", alpha = .5) +
  
  #make labs
  labs(x = "group rating", y = "second rating") +
  
  #theme
  theme_minimal()

#call plot
p1
```
Also making a binary version of this plot:

```{r}
data <- data %>% mutate(BinaryFeedback = sign(Feedback))
```


```{r}
p1 <- data %>%
  group_by(FirstRating, SecondRating) %>%
  summarise(mean_feedback = mean(Feedback), .groups = "drop") %>%
  
  ggplot(aes(x = FirstRating, y = SecondRating, fill = mean_feedback)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  geom_abline(linetype = "dashed", alpha = .5) +
  labs(x = "first rating", y = "second rating", fill = "avg feedback") +
  theme_minimal()

p1
```


```{r}
cor.test(x=data$FirstRating, y=data$SecondRating)
```

```{r}
cor.test(x=data$GroupRating, y=data$SecondRating)
```

```{r}
# just as a sanity check (this should be low.. but actually isn't)
cor.test(x=data$FirstRating, y=data$GroupRating)
```

