---
title: "sim_PBM"
output: html_document
---

```{r}
pacman::p_load(tidyverse)
```


Set up a proportional bayesian agent 

We assume a zero-sum attentional budget: the more weight
you give to your own rating the less you give to the group rating

Where:
Weight of 0 = ignores own 1st rating
Weight of 0.5 = equal weight to own 1st rating and Grating
Weight of 1 = ignores group rating

```{r}
### Setting up all the variables ####

second_rating <- c() #outcome variable

first_rating <- sample(0:7, 158, replace = TRUE) #Sampling 158 random values between 0-7
group_rating <- integer(length(first_rating)) #Defining group_rating so its ready for the loop

condition <- sample(rep(1:3, length.out = length(first_rating))) #Sampling 158 conditions equally divided between 1-3

#For loop that depending on the condition assigns values to group_rating, according to what they did in the original paper
for (i in 1:length(first_rating)) {
  if (condition[i] == 1) {
    group_rating[i] <- first_rating[i] #Equal to first rating
  } else if (condition[i] == 2) {
    group_rating[i] <- first_rating[i] - sample(2:3, 1) #Lower than first rating
  } else {
    group_rating[i] <- first_rating[i] + sample(2:3, 1) #higher than first rating
  }
  
  group_rating[i] <- as.integer(max(0, min(7, group_rating[i]))) #Make sure its between 0-7
}

p = 0.7 # Setting the weight to be slightly more trusting in ones own 1st rating

prob_rating <- c() #probability of rating


```

```{r}
### Simulate second_rating behavior ###

for (i in 1:length(first_rating)) {
  alpha_post <- 0.5 + p * first_rating[i] + (1 - p) * group_rating[i] #The evidence for a high rating
  beta_post  <- 0.5 + p * (7 - first_rating[i]) + (1 - p) * (7 - group_rating[i]) #The evidence for a low rating

  prob_rating[i] <- rbeta(1,alpha_post, beta_post)
  
  second_rating[i] <- rbinom(1,7,prob_rating[i])
}


```

```{r}
### Create df and save to csv ###
df <- data.frame(
  first_rating = first_rating,
  group_rating = group_rating,
  second_rating = second_rating,
  prob_rating = prob_rating
)

write.csv(df, "PBA_simdata.csv", row.names = FALSE)

```

## refactor as function
```{r}
# Generate a second rating given a first rating, second rating and weights
WBA_agent <- function(w_direct, w_social, first_rating, group_rating){
  
  #get alpha
  alpha = 0.5 + w_direct * first_rating + w_social * group_rating
  
  #get beta
  beta = 0.5 + w_direct * (7-first_rating) + w_social * (7 - group_rating) 
  
  #draw a rate
  rate <- rbeta(n=1, alpha, beta)
  
  #feed to binom
  choice <- rbinom(n=1, size=7, rate)
  
  list(choice = choice)
  
}

#vectorized so it can be used 
WBA_agent <- function(w_direct, w_social, first_rating, group_rating){
  
  #get length for determining number of draws alter
  n <- length(first_rating)

  #calc alpha and beta values to feed to beta dist 
  alpha = 0.5 + w_direct * first_rating + w_social * group_rating
  beta  = 0.5 + w_direct * (7-first_rating) + w_social * (7-group_rating)

  #draw a rate
  rate <- rbeta(length(alpha), alpha, beta)
  
  #turn rate into a choice
  choice <- rbinom(length(alpha), size=7, rate)

  choice
}


```

## scenario config
```{r}

n_trials = 100 #** 
weight_direct = 1
weight_social = 1

#read in 1st and group ratings
first_and_group_df <- read_csv("1st_and_group_ratings.csv")

test_data <- first_and_group_df %>% 
  mutate(second_rating = WBA_agent(1, 0.5, first_ratings, group_ratings)) 

write_csv(test_data, "test_data_wba_wd1_w05.csv")
```


